NAME = replace

CC= clang++

FLAGS = -Wall -Wextra -Werror -std=c++98

SRCS=	main.cpp

OBJS=	$(SRCS:.cpp=.o)

.c.o :
	$(CC) $(FLAGS) -c $< -o $(<:.c=.o)

$(NAME): $(OBJS)
	$(CC) $(FLAGS) $(OBJS) -o $(NAME)

:
	rm -f $(OBJS)

f:	
	rm -f $(NAME)

all:	$(NAME)

re:		f all

.PHONY:	 f all re
